// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh5K2z-9RDM_cHCI5EpYYRNcItVPmAp2c',
    appId: '1:820441840325:web:0521b88607468d88ec4eac',
    messagingSenderId: '820441840325',
    projectId: 'qiraat-bf2e6',
    authDomain: 'qiraat-bf2e6.firebaseapp.com',
    storageBucket: 'qiraat-bf2e6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNHeBVp601uvRQTj2KG-Pn0IOnIOHVe5E',
    appId: '1:820441840325:android:ca81126d9b4df9e4ec4eac',
    messagingSenderId: '820441840325',
    projectId: 'qiraat-bf2e6',
    storageBucket: 'qiraat-bf2e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB366Jfy0Lz66YyMT51yfeo7Ec2B0n-d1c',
    appId: '1:820441840325:ios:d5ed6fa3e6cda119ec4eac',
    messagingSenderId: '820441840325',
    projectId: 'qiraat-bf2e6',
    storageBucket: 'qiraat-bf2e6.firebasestorage.app',
    iosBundleId: 'com.AScode.qiraat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB366Jfy0Lz66YyMT51yfeo7Ec2B0n-d1c',
    appId: '1:820441840325:ios:d5ed6fa3e6cda119ec4eac',
    messagingSenderId: '820441840325',
    projectId: 'qiraat-bf2e6',
    storageBucket: 'qiraat-bf2e6.firebasestorage.app',
    iosBundleId: 'com.AScode.qiraat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh5K2z-9RDM_cHCI5EpYYRNcItVPmAp2c',
    appId: '1:820441840325:web:51486c7136532f6aec4eac',
    messagingSenderId: '820441840325',
    projectId: 'qiraat-bf2e6',
    authDomain: 'qiraat-bf2e6.firebaseapp.com',
    storageBucket: 'qiraat-bf2e6.firebasestorage.app',
  );
}
